### ISSUE TITLE
Possible conflicting dependencies

### ISSUE THREAD

**Issue by toytonic** [localytics/react-native-template-app#1]
Hi,

While integrating localytics-react-native in our project we ran into the following issue:

`com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzee`

which is caused by possible conflicting dependencies ('com.google.android.gms:play-services-ads:9.4.0').

To solve it, I had to remove the dependency in the `build.gradle` your lib. IHMHO the lib lib should not have those dependencies but only require the developers to integrate them on project level.

What do you think?

**Comment by abashyam** [comment]
the SDK uses the ads framework for analytics and would require them. It would appropriate to document that the ad's framework should be excluded from the compile if the project intends to use a different version.
