### ISSUE TITLE
ios Build broken on 2.1.2 . for React 0.55.4

### ISSUE THREAD

**Issue by hernancorigliano** [localytics/react-native-template-app#12]
Installing the `localytics-react-native` package and using` Cocoapods 1.5` for the ios App, brings compilation errors for the Pod with error messsage` 'Cannot build Module Localytics'` at lines `'@import Localytics'`  in the source files.

**Comment by abashyam** [comment]
Can you should additional information including build logs. Feel Free to reach out to support@localytics.com and reference an existing JIRA Issue BUG-2275.

Localytics-react-native doesn't use CocoaPods.  The sample does import Localytics module and successfully.

Not sure if CocoaPods is used to install Localytics module. That is no longer supported as the react native module is closely tied to the Framework. localytics-react-native already includes the Framework.

Please ensure the target which imports Localytics Module actually gas Framework Search path that contains $(PROJECT_DIR)/../node_modules/localytics-react-native/ios/Frameworks

**Comment by hernancorigliano** [comment]
I end up making a custom podspec to integrate the package through cocoapods.
